12 financial product fields
coopiteasy/investor-wallet-platform pull request #19
Opened 2019-10-22 20:22 UTC by houssine78

Adding fields to financial products and loan issue models and views

2019-10-23 07:56 UTC, robinkeunen commented
Heu ça a l'air plus ou moins bon à la fin mais j'ai l'impression que tu as pas bien fait ton rebase. Et il faut cleaner avant de merger. Tu veux que je te le fasse?

2019-10-23 07:56 UTC, robinkeunen requested changes
Heu ça a l'air plus ou moins bon à la fin mais j'ai l'impression que tu as pas bien fait ton rebase. Et il faut cleaner avant de merger. Tu veux que je te le fasse?

2019-10-23 08:42 UTC, robinkeunen approved these changes

2019-10-23 08:43 UTC, robinkeunen commented
@houssine78 vwala, c'est propre. J'ai rereviewé vite fait du coup et ça m'a l'air bon.

Juste, 🙏configure ton IDE pour mettre des espaces dans tes tabulations xml 🙏

2019-10-23 08:45 UTC, robinkeunen commented
T'avais fait un merge de la 12 dans ta branche à un moment, en committant les conflits, ça a foutu le casin. Pis yavait des rebase un peu sauvage qui ont donnée des commits dupliqués. toussa toussa.

2019-10-24 08:30 UTC, houssine78 commented
@robinkeunen voilà c'est fait. Tab remplacé par 4 spaces ;)

2019-10-24 08:30 UTC, merged